#central location to maintain gems for whole project
source 'https://rubygems.org'

gem 'cucumber'
gem 'watir'
gem 'rspec'
gem 'page-object'
gem 'selenium-webdriver'
gem 'launchy'
gem 'yml_reader'
gem 'yaml'
